
version: "3.1"

services:
  # Existing MariaDB containers
  customer_db:
    image: mariadb
    container_name: customer
    restart: always
    ports:
      - 3307:3306
    environment:
      MARIADB_DATABASE: customer
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - ./Databases/customer:/docker-entrypoint-initdb.d

  employee_db:
    image: mariadb
    container_name: employee
    restart: always
    ports:
      - 3308:3306
    environment:
      MARIADB_DATABASE: employee
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - ./Databases/employee:/docker-entrypoint-initdb.d

  order_db:
    image: mariadb
    container_name: order
    restart: always
    ports:
      - 3309:3306
    environment:
      MARIADB_DATABASE: order
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - ./Databases/order:/docker-entrypoint-initdb.d

  product_db:
    image: mariadb
    container_name: product
    restart: always
    ports:
      - 3310:3306
    environment:
      MARIADB_DATABASE: product
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - ./Databases/product:/docker-entrypoint-initdb.d

  tax_db:
    image: mariadb
    container_name: tax
    restart: always
    ports:
      - 3311:3306
    environment:
      MARIADB_DATABASE: tax
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - ./Databases/tax:/docker-entrypoint-initdb.d

  ticket_db:
    image: mariadb
    container_name: ticket
    restart: always
    ports:
      - 3312:3306
    environment:
      MARIADB_DATABASE: ticket
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - ./Databases/ticket:/docker-entrypoint-initdb.d

  logs:
    image: mariadb
    container_name: action_logs
    restart: always
    ports:
      - 3313:3306
    environment:
      MARIADB_DATABASE: action_logs
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - ./Databases/logs:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    container_name: sda2_adminer
    restart: always
    ports:
      - 8080:8080
